# Created by: Li-Wen Hsu <lwhsu@lwhsu.org>
# $FreeBSD: head/devel/py-argparse/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	argparse
PORTVERSION=	1.2.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Optparse-inspired command-line parsing library

LICENSE=	PSFL

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
