# Created by: Li-Wen Hsu <lwhsu@lwhsu.org>
# $FreeBSD: head/devel/py-argparse/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	argparse
PORTVERSION=	1.2.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Optparse-inspired command-line parsing library

LICENSE=	PSFL

USES=		python
USE_PYTHON=	distutils autoplist
PYDISTUTILS_INSTALLNOSINGLE=	yes

.include <bsd.port.mk>
