# Created by: Emil Smolenski <am+bsd@nereis.pl>
# $FreeBSD$

PORTNAME=	ingo
PORTVERSION=	0.0.0.20160415
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	am+bsd@nereis.pl
COMMENT=	Go library helping you to persist flags in a ini-like config file

LICENSE=	ISCL

USES=		go
USE_GITHUB=	yes
GH_ACCOUNT=	schachmat
GH_TAGNAME=	b1887f8

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${PORTNAME}

.include <bsd.port.mk>
