# Created by: renchap@cocoa-x.com
# $FreeBSD: net/rubygem-bunny/Makefile 323791 2013-07-27 14:33:52Z swills $

PORTNAME=	bunny
PORTVERSION=	0.6.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Another synchronous Ruby AMQP client

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
