# Created by: Emil Smolenski <am+bsd@nereis.pl>
# $FreeBSD$

PORTNAME=	isatty
PORTVERSION=	0.0.0.20160302
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	am+bsd@nereis.pl
COMMENT=	isatty for golang

LICENSE=	MIT

USES=		go
USE_GITHUB=	yes
GH_ACCOUNT=	mattn
GH_PROJECT=	${PKGNAMEPREFIX}${PORTNAME}
GH_TAGNAME=	56b76bd

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${GH_PROJECT}

.include <bsd.port.mk>
