# Created by: Emil Smolenski <am+bsd@nereis.pl>
# $FreeBSD$

PORTNAME=	isatty
PORTVERSION=	0.0.0.20160302
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	am+bsd@nereis.pl
COMMENT=	isatty for golang

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	mattn
GH_PROJECT=	${PKGNAMEPREFIX}${PORTNAME}
GH_TAGNAME=	56b76bd

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${GH_PROJECT}

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
